{% set name = "sheldon" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rossmacarthur/sheldon/archive/{{ version }}.tar.gz
  sha256: 5d8ecd432a99852d416580174be7ab8f29fe9231d9804f0cc26ba2b158f49cdf

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - curl
    - libcurl
    - openssl
    - zlib

test:
  commands:
    - sheldon --help

about:
  home: https://sheldon.cli.rs
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, configurable, shell plugin manager
  dev_url: https://github.com/rossmacarthur/sheldon

extra:
  recipe-maintainers:
    - danielnachun
