context:
  version: "0.8.2"

package:
  name: sheldon
  version: ${{ version }}

source:
  url: https://github.com/rossmacarthur/sheldon/archive/${{ version }}.tar.gz
  sha256: 8b9306902849344bacb9525051c88b34487767086adc93936fdef98c8650cfc8

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - curl
    - libcurl
    - openssl
    - zlib

tests:
  - script:
      - sheldon --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, configurable, shell plugin manager
  homepage: https://sheldon.cli.rs
  repository: https://github.com/rossmacarthur/sheldon

extra:
  recipe-maintainers:
    - danielnachun
