context:
  version: "0.8.1"

package:
  name: sheldon
  version: ${{ version }}

source:
  url: https://github.com/rossmacarthur/sheldon/archive/${{ version }}.tar.gz
  sha256: fa0aade40a2e2f397f5f8734a0bc28391147ed6ad75c087f8ab7db7ce1e49b88

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - curl
    - libcurl
    - openssl
    - zlib

tests:
  - script:
      - sheldon --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, configurable, shell plugin manager
  homepage: https://sheldon.cli.rs
  repository: https://github.com/rossmacarthur/sheldon

extra:
  recipe-maintainers:
    - danielnachun
