context:
  version: "0.8.3"

package:
  name: sheldon
  version: ${{ version }}

source:
  url: https://github.com/rossmacarthur/sheldon/archive/${{ version }}.tar.gz
  sha256: fea159b473a9ae48779ae2094eb909262361f45d2bf3a2e3968eddacb8e3b992

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - curl
    - libcurl
    - openssl
    - zlib

tests:
  - script:
      - sheldon --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, configurable, shell plugin manager
  homepage: https://sheldon.cli.rs
  repository: https://github.com/rossmacarthur/sheldon

extra:
  recipe-maintainers:
    - danielnachun
