context:
  version: 0.8.0

package:
  name: sheldon
  version: ${{ version }}

source:
  url: https://github.com/rossmacarthur/sheldon/archive/${{ version }}.tar.gz
  sha256: 71c6c27b30d1555e11d253756a4fce515600221ec6de6c06f9afb3db8122e5b5

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - curl
    - libcurl
    - openssl
    - zlib

tests:
  - script:
      - sheldon --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, configurable, shell plugin manager
  homepage: https://sheldon.cli.rs
  repository: https://github.com/rossmacarthur/sheldon

extra:
  recipe-maintainers:
    - danielnachun
